spring:
  application:
    name: ${APP_NAME:RESTAURANTES_API}

  security:
    user:
      name: ${ACTUATOR_USERNAME}
      password: ${ACTUATOR_PASSWORD}
      roles: ADMIN

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:DEBUG}
    properties:
      hibernate:
        format_sql: true
        default_schema: public

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN
  security:
    enabled: true
    roles: ADMIN

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:restaurantes-api-app}

# Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL:DEBUG}
    com.virosms.restaurantreservationchallenge: ${LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${SHOW_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

# App Information
app:
  name: ${APP_NAME:RESTAURANTES_API}
  version: ${APP_VERSION:1.0.0}